stages:
  - build

release:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet build -o release -c Release /app/LethalMod.sln
  artifacts:
    paths:
      - ./release/LethalMod.dll
